### ISSUE TITLE
Align parsing of the `req` parameter with VCL and petridish

### ISSUE THREAD

**Issue by tripodsan** [adobe/hypermedia-pipeline#36]
the `req` param is currently parsed as JSON. as mentioned in https://github.com/adobe/helix-cli/issues/126 this might change.

**Comment by trieloff** [comment]
And in adobe/helix-cli#126 what is `req.params` here is passed as `params` request parameter there.

**Comment by tripodsan** [comment]
currently the pipeline gets already the dissected payload/action, as https://github.com/adobe/hypermedia-pipeline/issues/7#issuecomment-417301894.

the openwhisk `params.req` is the encoded external request, and will become `payload.request`.
the openwhisk `__ow_*` is the internal request, and those properties become `action.request`

**Comment by trieloff** [comment]
I don't think we can effectively encode the entire request and put it in `params.req` because:
- generating JSON in VCL is error-prone
- most of the interesting stuff (headers) are already passed in `__ow_headers` anyway

But we can have 
- one route for headers (through `__ow_headers`, to be put into `payload.request.headers`) 
- one route for params (through `params.params` (url encoded), to be put into `payload.request.params`)
- one route for method (through `params.method`, to be put into `payload.request.method`)
