### ISSUE TITLE
Provide (V)DOM API for HTML

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#43]
See adobe/project-helix#305

**Comment by kptdobe** [comment]
I started to create the Bootstrap Grayscale example based on what we did during the hackathon. See WIP https://github.com/kptdobe/helix-bootstrap-grayscale.

Even though the API is not there, I mimic the API with some simple methods and I not really if this is where we want to go. See https://github.com/kptdobe/helix-bootstrap-grayscale/blob/master/src/html.pre.js#L40-L56

Whatever is the API called, this collection of DOM moves, wraps and decorations is what we'll end up doing to re-format the DOM to something which is design / css friendly. And this is really cumbersome to do and feels.. completely wrong!

cc @cwoeltge @simonwex @trieloff @markusheer @tripodsan

**Comment by trieloff** [comment]
It looks a bit like a person with a hammer went to put some screws into a wall. I guess some of the transitions (especially `wrap`) might be done more elegantly in HTL. 

Are there good language that we can use for the problem domain of DOM2DOM transformations?

**Comment by kptdobe** [comment]
That's where I wanted to go: I think now that DOM2DOM transformations via APIs is completely unnatural and wrong. 
As you mention, it would be more elegant in HTL which would mean that each section has an HTL representation that you might overwrite or create your own sections at project level. But then the expected input would be a JSON-like object (section.img.src or section.heading.text), not hast. mdast is close but might not be good neither because we'll keep having checks on the children objects (is child x an img or heading level 2).
I think we should still research on a good way to represent the "content" after the md transformation.

**Comment by trieloff** [comment]
Here is an example what an array of sections with enhanced metadata could look like: https://github.com/adobe/hypermedia-pipeline/blob/29bda05d6ff5841de85469f54a458e7b32f73df2/test/fixtures/sectionsmetadata.json

We could also think about having a more compressed mdast-like structure as mentioned in #24 

Or: we could allow mdast2htast transformations with custom handlers, i.e. something like this:

```javascript

const converter = require('mdast-converter');

// matches using css-like expressions
// handles using an htl template
converter.match('list item:has(a)', require('list-item.htl'));

return { content: { htast: converter.convert(content.mdast) }};
```

**Comment by kptdobe** [comment]
I am currently refactoring my example to go in the "define sections as htl" direction. Let see where it goes.

**Comment by trieloff** [comment]
Fixed the example. For Noah, I've suggested #50

**Comment by kptdobe** [comment]
I created a branch in the Grayscale repo and built the example using the "sectionizer" (first 2 sections only for now). `pre.js` is empty and the HTL file contains the templates to output the sections, see https://github.com/kptdobe/helix-bootstrap-grayscale/blob/42-sectionizer/src/html.htl#L53-L82

I can mostly use the sections as is (everything needed is computed for me), except here: https://github.com/kptdobe/helix-bootstrap-grayscale/blob/42-sectionizer/src/html.htl#L58
```
<h2 class="text-white-50 mx-auto mt-2 mb-5">${section.children[2].children[0].value}</h2>
```

If Noah in the LayoutMachine has the capability to define the sections but also prepare the data - something like:

```
{
   type: 'root',
   title: 'h1 title',
   title2: 'h2 title',
   intro: 'first paragraph'
   ...
}
```

Mark can only focus on the HTL part and does not need any API...

**Comment by trieloff** [comment]
@kptdobe in the light of the discovery that we can easily use JSX (adobe/helix-cli#203) in our scripts, this matcher/transformer API might be even more useful. 

We would provide an MDAST to VDOM transformer that can be overloaded with custom matchers. All you have to do is to provide a function that returns a VDOM node or string (we transform on the fly).

**Comment by trieloff** [comment]
> If Noah in the LayoutMachine has the capability to define the sections but also prepare the data

So in `LayoutMachine` you would call

```javascript
const machine = require('layoutmachine')
  .match('heading? image image image+', (section) => {
    // gallery
    return { type: 'gallery', images: section.children.filter(child => child.type==='image').map(child => child.url) };
  });

content.sections = machine.process(content.sections);
```

The `match` syntax is a riff on #50, i.e. regular expressions on sequences of section types.

**Comment by kptdobe** [comment]
Yes, the LayoutMachine is something to try, looks promising, especially if it can shape the output section so that we do not need an extra VDOM API on top!

Not sure where the JSX story would help here... We need a place where to put the templates for the sections. By default, the mdast to hast to html transformation is enough (simple collection of section + h* + img + p), we would only need to cover the override case which could be done in an external HTL (JSX?) file. We could even add some magic to find those overrides automatically by the section type and inject the rendering in the `html` property so that the html.htl could stay super simple (just output 
 all sections).
