### ISSUE TITLE
Improve Documentation of Pipeline Types and Helper Functions

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#55]
We should update README.md to reflect the changes to `payload` and `action`. @tripodsan @kptdobe

**Comment by tripodsan** [comment]
I'm thinking of how we could leverage JSDoc do declare the structures we use and how we converge towards a global documentation. i.e. somewhere the role of the `pre.js` needs to be documented as well. but currently the `pre.js` is an implementation detail of `helix-cli`.

however, since most of the logic is provided by this _hypermedia-pipeline_, we might start writing a documentation in this project and mention helix-cli as example projects that make use of this pipeline.

**Comment by trieloff** [comment]
I wonder if we could go a step further and create proper type definitions in Typescript like this https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html which would give us Intellisense in VS Code, too.

**Comment by trieloff** [comment]
And we can generate Markdown documentation, too: https://www.npmjs.com/package/typedoc-plugin-markdown

**Comment by tripodsan** [comment]
...but I don't want to switch to typescript :-)

Having [typedefs via JSDOC](http://usejsdoc.org/tags-typedef.html), is also understood by the IDEs and enables intellisense.

**Comment by trieloff** [comment]
We will still write code in JavaScript and simply create an `index.d.ts` file that has the type definitions.

**Comment by trieloff** [comment]
Ok, I've tried my hands unsuccessfully at the Typedoc Markdown plugin and I'm ready to dismiss it.

The things I'm looking for are:

- ability to generate documentation in Markdown
- IntelliSense autocompletion for developers
- Automatic verification that fails when non-documented properties show up during testing

**Comment by kptdobe** [comment]
Why not https://github.com/jsdoc2md/jsdoc-to-markdown for the first part ?
